# Generated by Django 4.2.1 on 2023-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="mobile",
            field=models.IntegerField(),
        ),
    ]
