# Generated by Django 4.2.1 on 2023-05-18 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_guest_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="date",
        ),
    ]
